#!/usr/bin/php
<?php

// so the bot don't stop
set_time_limit(0);

function __autoload($className) {

	$sep = DIRECTORY_SEPARATOR;

	// Replace _ with / to load classes from sub-directories
	$file = str_replace(
		'_', $sep, strtolower($className) . '.php'
	);

	// load events from events-available directory
	// load plugins from plugins directory
	// default is to load files from system dir
	$paths = array(
		// 20-slap.php: match[1] = slap.php
		'events-available' => '^event' . $sep . "[\d+-]?(.+)",
		'plugins' => '^plugin' . $sep . "(.+)",
		'system' => '(.*)'
	);

	foreach ($paths as $directory => $pattern) {
		if (preg_match("|$pattern|", $file, $match)) {
			$file = $directory . $sep . array_pop($match);
			break;
		}
	}
	
	if (file_exists($file)) {
		require($file);
		
		if (!class_exists($className)) {
			die("Loaded file $file but $className not found within.");
		}
	} else {
		die("Cannot load class '$className', file does not exist: $file\n");
	}

}

require("config.php");

$eva = new Eva($config);
$eva->run();
